######################################################################
# Automatically generated by qmake (3.1) Sat Sep 24 17:27:20 2026
######################################################################

TEMPLATE = app
TARGET = 2048-qt

QT += qml quick widgets quickwidgets

DEFINES += APP_VERSION=\\\"1.0.0\\\"

INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += src/myclass.h src/settings.h src/dialogmanager.h
SOURCES += src/main.cpp src/myclass.cpp src/settings.cpp src/dialogmanager.cpp

lupdate_only {
SOURCES += qml/main.qml \
           qml/Tile.qml \
           qml/2048.js
}

RESOURCES += resources.qrc
TRANSLATIONS += ts/2048-qt_de_DE.ts \
                ts/2048-qt_fr_FR.ts \
                ts/2048-qt_pl_PL.ts \
                ts/2048-qt_ru_RU.ts \
                ts/2048-qt_zh_CN.ts
